// ইংরেজি অনুবাদ। key = সোর্স কোডে থাকা মূল বাংলা লেখা।
// এখানে যে key নেই, GetX সেটির বদলে key নিজেই দেখাবে (অর্থাৎ বাংলা লেখাটি)।
const Map<String, String> enUS = {
  // ── ড্রয়ার নেভিগেশন ──
  'নতুন পণ্য যোগ করুন': 'Add product',
  'স্টক ও ক্রয়': 'Stock & purchase',
  'কাস্টমার ও SR': 'Customers & SR',
  'রিপ্লেস অনুরোধ': 'Replace requests',
  'লাভ গণনা: শুধুমাত্র delivered orders | COGS = purchasePrice × qty':
      'Profit is calculated from delivered orders only | COGS = purchasePrice × qty',
  'সব product document-এ missing fields যোগ হবে (যেমন: isInternal, createdAt ইত্যাদি)। যেসব documents ইতিমধ্যে সম্পূর্ণ সেগুলো পরিবর্তন হবে না।':
      'Missing fields (e.g. isInternal, createdAt) will be added to every product document. Documents that are already complete will not be changed.',
  // ── সাধারণ / Common ──
  'হ্যাঁ': 'Yes',
  'না': 'No',
  'বাতিল': 'Cancel',
  'বাতিল করুন': 'Cancel',
  'সংরক্ষণ': 'Save',
  'সংরক্ষণ করুন': 'Save',
  'সেভ': 'Save',
  'সেভ করুন': 'Save',
  'সেভ হয়েছে': 'Saved',
  'সেভ হয়েছে!': 'Saved!',
  'সেভ হচ্ছে…': 'Saving…',
  'সেভ হচ্ছে...': 'Saving…',
  'সাবমিট হচ্ছে…': 'Submitting…',
  'প্রক্রিয়া চলছে…': 'Processing…',
  'লোড হচ্ছে...': 'Loading…',
  'যোগ': 'Add',
  'যোগ করুন': 'Add',
  'যোগ হয়েছে': 'Added',
  '✓ যোগ হয়েছে': '✓ Added',
  'আপডেট': 'Update',
  'আপডেট করুন': 'Update',
  'আপডেট হয়েছে': 'Updated',
  'সম্পাদনা': 'Edit',
  'এডিট': 'Edit',
  'পরিবর্তন': 'Change',
  'মুছুন': 'Delete',
  'মুছে ফেলুন': 'Delete',
  'মুছে ফেলা হয়েছে': 'Deleted',
  'মুছে দেবেন?': 'Delete this?',
  'ডিলিট': 'Delete',
  'ডিলিট করুন': 'Delete',
  'ডিলিট হয়েছে': 'Deleted',
  'ডিলিট করবেন?': 'Delete?',
  'ডিলেট': 'Delete',
  'ডিলেট করুন': 'Delete',
  'ডিলেট হয়েছে': 'Deleted',
  'হ্যাঁ, মুছুন': 'Yes, delete',
  'হ্যাঁ, ডিলিট': 'Yes, delete',
  'হ্যাঁ, ক্লিয়ার': 'Yes, clear',
  'রিমুভ করুন': 'Remove',
  'রিমুভ করবেন?': 'Remove this?',
  'সরিয়ে দিন': 'Remove',
  'বাদ দিন': 'Remove',
  'নিশ্চিত করুন': 'Confirm',
  'ঠিক আছে': 'OK',
  'এখন না': 'Not now',
  'বন্ধ করুন': 'Close',
  'সফল': 'Success',
  'সফল!': 'Success!',
  'সম্পন্ন': 'Done',
  'সম্পন্ন!': 'Done!',
  'ত্রুটি': 'Error',
  'সতর্কতা': 'Warning',
  'ব্যর্থ হয়েছে': 'Failed',
  'আবার চেষ্টা করুন': 'Try again',
  'রিফ্রেশ': 'Refresh',
  'ফিল্টার': 'Filter',
  'প্রয়োগ': 'Apply',
  'ক্লিয়ার': 'Clear',
  'সব': 'All',
  'সকল পণ্য': 'All products',
  'সব দেখুন': 'View all',
  'শুরু': 'From',
  'শেষ': 'To',
  'শুরু করুন': 'Start',
  'আরো': 'More',
  'অপশন': 'Options',
  'বিবরণ': 'Details',
  'বিস্তারিত দেখুন': 'View details',
  'তালিকায় ফিরুন': 'Back to list',
  'লিখুন': 'Enter',
  'খুঁজুন...': 'Search…',
  'খুঁজুন…': 'Search…',
  'সার্চ করুন...': 'Search…',
  'কপি করুন': 'Copy',
  'কপি হয়েছে': 'Copied',
  'কপি হয়েছে!': 'Copied!',
  'তারিখ': 'Date',
  'পরিমাণ': 'Quantity',
  'পরিমাণ *': 'Quantity *',
  'পরিমাণ:': 'Quantity:',
  'পরিমাণ: ': 'Quantity: ',
  'পরিমাণ (৳)': 'Amount (৳)',
  'পরিমাণ লিখুন': 'Enter amount',
  'সঠিক পরিমাণ দিন': 'Enter a valid quantity',
  'সঠিক সংখ্যা লিখুন': 'Enter a valid number',
  'মোট': 'Total',
  'টাকা': 'Taka',
  'টি': ' pcs',
  'মূল্য': 'Price',
  'মূল্য লিখুন': 'Enter price',
  'নোট': 'Note',
  'নোট (ঐচ্ছিক)': 'Note (optional)',
  'মন্তব্য (ঐচ্ছিক)': 'Comment (optional)',
  'বিবরণ (ঐচ্ছিক)': 'Description (optional)',

  // ── সময়কাল / Period ──
  'আজ': 'Today',
  'আজকে': 'Today',
  'গতকাল': 'Yesterday',
  'সপ্তাহ': 'Week',
  'মাস': 'Month',
  'কাস্টম': 'Custom',
  'তারিখ রেঞ্জ': 'Date range',
  'এই সপ্তাহ': 'This week',
  'এই মাস': 'This month',
  'চলতি মাস': 'Current month',
  'আগের মাস': 'Previous month',
  'পরের মাস': 'Next month',
  'সময়কাল': 'Period',
  'মাসিক': 'Monthly',
  'সাপ্তাহিক': 'Weekly',
  'মাস ও সাল বেছে নিন': 'Pick month and year',

  // ── লগইন / Auth ──
  'Email ও Password দিন': 'Enter email and password',
  'Email বা Password ভুল': 'Wrong email or password',
  'Password ভুল': 'Wrong password',
  'এই email এ কোনো account নেই': 'No account exists with this email',
  'অনেক বার চেষ্টা হয়েছে, কিছুক্ষণ পর চেষ্টা করুন':
      'Too many attempts, please try again later',

  // ── হোম / Dashboard ──
  'Data নেই': 'No data',
  'Theme পরিবর্তন করুন': 'Change theme',
  'আপনি কি Logout করতে চান?': 'Do you want to log out?',
  'নতুন অর্ডার': 'New order',
  'বিক্রয় পরিকল্পনা': 'Sales plan',
  'রিপ্লেস': 'Replace',
  'রিপ্লেস ম্যানেজমেন্ট': 'Replace management',
  'সাপ্লাইয়ার': 'Supplier',
  'স্টক ইন': 'Stock in',
  'স্টক আউট / Dispatch': 'Stock out / Dispatch',

  // ── ডিসপ্যাচ / Dispatch ──
  'Dispatch করা হচ্ছে…': 'Dispatching…',
  'Dispatch করুন': 'Dispatch',
  'Dispatch করার মতো কোনো Approved অর্ডার নেই':
      'No approved orders available to dispatch',
  'কোনো Delivered অর্ডার নেই': 'No delivered orders',
  'বাল্ক Dispatch': 'Bulk dispatch',
  'সব সিলেক্ট': 'Select all',
  'সব বাতিল': 'Clear selection',
  'সকল অর্ডারের জন্য মেমো নাম্বার': 'Memo number for all orders',
  'মেমো / চালান নাম্বার': 'Memo / challan number',
  'মেমো নাম্বার দিতে হবে': 'Memo number is required',
  'মেমো নাম্বার লিখুন': 'Enter memo number',
  'অর্ডার সংখ্যা': 'Order count',
  'প্রডাক্ট সংখ্যা': 'Product count',
  'প্রক্রিয়াধীন': 'In progress',
  'কাস্টমার নাম বা Order ID...': 'Customer name or order ID…',
  'কাস্টমার নাম, Order ID বা মেমো নাম্বার দিয়ে খুঁজুন…':
      'Search by customer name, order ID or memo number…',
  'সতর্কতা: Dispatch করলে স্টক কেটে যাবে। এটি undo করা যাবে না।':
      'Warning: dispatching will deduct stock. This cannot be undone.',
  'স্টক আউট ব্যর্থ': 'Stock out failed',
  'স্টক ফিরে যাবে': 'Stock will be returned',

  // ── খরচ / Expense ──
  'খরচ': 'Expense',
  'খরচ যোগ': 'Add expense',
  'খরচ যোগ করুন': 'Add expense',
  'নতুন খরচ যোগ': 'Add new expense',
  'নতুন খরচ যোগ করুন': 'Add a new expense',
  'খরচ মুছবেন?': 'Delete this expense?',
  'খরচ ডিলিট?': 'Delete expense?',
  'এই মাসে কোনো খরচ নেই': 'No expenses this month',
  'কোনো খরচ নেই': 'No expenses',
  'মোট খরচ': 'Total expense',
  'এই খরচ এন্ট্রি মুছে ফেলা হবে।': 'This expense entry will be deleted.',
  'ধরন': 'Type',
  'পরিবহন': 'Transport',
  'বিদ্যুৎ': 'Electricity',
  'ভাড়া': 'Rent',
  'বেতন': 'Salary',
  'খাত (যেমন: কাগজ, কলম)': 'Category (e.g. paper, pen)',

  // ── ফিন্যান্স / Finance ──
  'At Shop রিপ্লেস': 'At-shop replace',
  'Supplier রিপ্লেস': 'Supplier replace',
  'Date Range বেছে নিন': 'Pick a date range',
  'SR মাসিক ফিক্সড বেতন': 'SR monthly fixed salary',
  'wholesale − cost পার্থক্য': 'Wholesale − cost difference',
  'এই period এ delivered order নেই': 'No delivered orders in this period',
  'এই period এ কোনো purchase/sales নেই': 'No purchases or sales in this period',
  'কেনা': 'Purchased',
  'বিক্রি': 'Sold',
  'নেট': 'Net',
  'কেনা দামে স্টক': 'Stock at cost price',
  'বিক্রয় মূল্যে স্টক': 'Stock at selling price',
  'ক্রয় মূল্য (COGS)': 'Cost of goods sold (COGS)',
  'গড় লাভের হার': 'Average margin',
  'চূড়ান্ত নিট লাভ (খরচ বাদে)': 'Final net profit (after expenses)',
  'দিনওয়ারি Purchase vs Sales': 'Daily purchase vs sales',
  'বিক্রয় মূল্য − ক্রয় মূল্য': 'Selling price − cost price',
  'বেতন বরাদ্দ': 'Salary allocation',
  'মোট wholesale মূল্য × স্টক পরিমাণ': 'Total wholesale price × stock quantity',
  'মোট কেনা মূল্য × স্টক পরিমাণ': 'Total cost price × stock quantity',
  'মোট বিক্রি': 'Total sales',
  'মোট রিপ্লেস': 'Total replaces',
  'মোট লাভ (Gross)': 'Gross profit',
  'রিপ্লেস স্টক মূল্যায়ন (বর্তমান)': 'Replace stock valuation (current)',
  'সম্ভাব্য লাভ': 'Potential profit',
  'স্টক কেনা (Purchase In)': 'Stock purchased (purchase in)',
  'স্টক মূল্যায়ন (বর্তমান)': 'Stock valuation (current)',

  // ── অর্ডার / Order ──
  'অর্ডার': 'Order',
  'অর্ডার সমূহ': 'Orders',
  'সব অর্ডার': 'All orders',
  'অর্ডার তালিকা': 'Order list',
  'অর্ডার স্ট্যাটাস': 'Order status',
  'অর্ডার আপডেট ব্যর্থ': 'Order update failed',
  'অর্ডার ডিলিট করবেন?': 'Delete this order?',
  'অর্ডার ডিলিট করুন': 'Delete order',
  'অর্ডার ডিলিট হয়েছে': 'Order deleted',
  'অর্ডার কনফার্ম করুন': 'Confirm order',
  'অর্ডার নিশ্চিত করুন': 'Confirm order',
  'অর্ডার সফলভাবে তৈরি হয়েছে': 'Order created successfully',
  'অর্ডার ডেলিভারি কমিশন': 'Order delivery commission',
  'এই অর্ডার মুছে ফেলা হবে': 'This order will be deleted',
  'কোনো অর্ডার পাওয়া যায়নি': 'No orders found',
  'কোনো অর্ডার নেই': 'No orders',
  'আজকের অর্ডার': "Today's orders",
  'সাম্প্রতিক অর্ডার': 'Recent orders',
  'মোট অর্ডার': 'Total orders',
  'অর্ডার করুন': 'Place order',
  'অর্ডার কনফার্মে যান': 'Go to order confirmation',
  'কাস্টমারের পক্ষে অর্ডার করুন': 'Place order on behalf of a customer',

  // SR সম্পর্কিত অর্ডার ফিল্ড
  'SR দিন': 'Assign SR',
  'SR সরান': 'Remove SR',
  'SR নির্বাচন করুন': 'Select SR',
  'SR নির্বাচিত নেই': 'No SR selected',
  'SR দ্বারা ডেলিভার করা হয়েছে': 'Delivered by SR',
  'SR-এর কমিশন রেকর্ড আপডেট হয়েছে': 'SR commission record updated',
  'এই SR-এর কমিশন চূড়ান্ত করবেন? এটি SR-এর পেমেন্ট রেকর্ডে যুক্ত হবে।':
      "Finalise this SR's commission? It will be added to the SR payment record.",
  'কমিশন নিশ্চিত': 'Commission confirmed',
  'কমিশন নিশ্চিত করুন': 'Confirm commission',
  'কমিশন নিশ্চিত হয়েছে': 'Commission confirmed',

  // ক্রেতা / কাস্টমার
  'ক্রেতা': 'Buyer',
  'ক্রেতা নির্বাচিত নেই': 'No buyer selected',
  'ক্রেতা পরিবর্তন': 'Change buyer',
  'ক্রেতা পরিবর্তন হয়েছে': 'Buyer changed',
  'ক্রেতা পরিবর্তন হয়নি': 'Buyer not changed',
  'কোনো ক্রেতা পাওয়া যায়নি': 'No buyer found',
  'আগে ক্রেতা নির্বাচন করুন': 'Select a buyer first',
  'কাস্টমার': 'Customer',
  'কাস্টমার তথ্য': 'Customer info',
  'কাস্টমার নির্বাচন': 'Select customer',
  'কাস্টমার নির্বাচন করুন': 'Select a customer',
  'কোনো কাস্টমার পাওয়া যায়নি': 'No customers found',

  // পণ্য / কার্ট
  'পণ্য যোগ': 'Add product',
  'পণ্য যোগ করুন': 'Add a product',
  'পণ্যের তালিকা': 'Product list',
  'পণ্য তালিকা': 'Product list',
  'পণ্য নির্বাচন': 'Select product',
  'সব পণ্য': 'All products',
  'কোনো পণ্য নেই': 'No products',
  'কোনো পণ্য পাওয়া যায়নি': 'No products found',
  'কমপক্ষে একটি পণ্য যোগ করুন': 'Add at least one product',
  'কার্টে যোগ করুন': 'Add to cart',
  'কার্ট': 'Cart',
  'কার্ট খালি': 'Cart is empty',
  'প্রডাক্ট': 'Product',
  'প্রডাক্ট লিস্ট': 'Product list',
  'প্রডাক্ট লিস্ট আপডেট হয়েছে': 'Product list updated',
  'প্রডাক্ট এডিট করুন': 'Edit product',
  'প্রডাক্ট বেছে নিন': 'Pick a product',
  'কোনো প্রডাক্ট পাওয়া যায়নি': 'No products found',
  'সব প্রডাক্ট দেখুন': 'View all products',
  'সব প্রডাক্ট রিমুভ করা হয়েছে। Order টি খালি সেভ করবেন?':
      'All products removed. Save this order empty?',
  'ইন্টার্নাল': 'Internal',
  'মূল্য (প্রতি পিস)': 'Price (per unit)',
  'ক্রয় মূল্য': 'Cost price',
  'ক্রয়মূল্য লিখুন': 'Enter cost price',
  'ক্রয়মূল্য সম্পাদন': 'Edit cost price',
  'বিক্রয়মূল্য লিখুন': 'Enter selling price',
  'বিক্রয়মূল্য সম্পাদন': 'Edit selling price',

  // সার্চ প্লেসহোল্ডার
  'নাম বা কোড দিয়ে খুঁজুন...': 'Search by name or code…',
  'নাম বা কোড দিয়ে খুঁজুন…': 'Search by name or code…',
  'নাম বা কোড দিয়ে ফিল্টার করুন…': 'Filter by name or code…',
  'নাম বা ফোন দিয়ে খুঁজুন...': 'Search by name or phone…',
  'নাম বা ফোন দিয়ে খুঁজুন…': 'Search by name or phone…',
  'নাম / ফোন দিয়ে খুঁজুন...': 'Search by name / phone…',
  'নাম / ফোন দিয়ে খুঁজুন…': 'Search by name / phone…',
  'প্রডাক্ট খুঁজুন...': 'Search product…',
  'প্রডাক্ট খুঁজুন…': 'Search product…',
  'প্রডাক্ট নাম দিয়ে খুঁজুন…': 'Search by product name…',
  'পণ্যের নাম বা কোড দিয়ে খুঁজুন…': 'Search by product name or code…',
  'Shop নাম, ফোন নং বা Order ID দিয়ে খুঁজুন…':
      'Search by shop name, phone or order ID…',
  'Shop নাম, মালিক বা ফোন দিয়ে খুঁজুন…':
      'Search by shop name, owner or phone…',
  'Shop নাম, মালিক বা ফোন দিয়ে খুঁজুন...':
      'Search by shop name, owner or phone…',

  // ডেলিভারি ও পেমেন্ট
  'ডেলিভারি': 'Delivery',
  'ডেলিভারি SR': 'Delivery SR',
  'আজকের ডেলিভারি': "Today's deliveries",
  'ডেলিভারি পেমেন্ট': 'Delivery payment',
  'ডেলিভারি প্রসেসিং হচ্ছে...': 'Processing delivery…',
  'ডেলিভারি সম্পন্ন': 'Delivery complete',
  'ডেলিভারি সম্পন্ন হয়েছে': 'Delivery completed',
  'ডেলিভারি সম্পন্ন হয়েছে কিছু আপডেট ব্যর্থ হয়েছে':
      'Delivery completed, but some updates failed',
  '✓ ডেলিভারি সম্পন্ন': '✓ Delivery complete',
  'ডেলিভার্ড করুন': 'Mark as delivered',
  'ডেলিভারির তারিখ': 'Delivery date',
  'নির্ধারিত': 'Scheduled',
  'নির্ধারিত ডেলিভারি': 'Scheduled delivery',
  'নির্ধারিত ডেলিভারি তারিখ': 'Scheduled delivery date',
  'নির্ধারিত ডেলিভারি তারিখ (ঐচ্ছিক)': 'Scheduled delivery date (optional)',
  'কোনো নির্ধারিত ডেলিভারি নেই': 'No scheduled deliveries',
  'তারিখ দিন': 'Set date',
  'তারিখ মুছুন': 'Clear date',
  'তারিখ সম্পাদন': 'Edit date',
  'তারিখ নির্ধারিত নেই': 'No date set',
  'পেমেন্ট': 'Payment',
  'পেমেন্ট তথ্য': 'Payment info',
  'পেমেন্ট তথ্য সেভ হয়েছে': 'Payment info saved',
  'পেমেন্ট আপডেট করুন': 'Update payment',
  'পেমেন্ট মাধ্যম': 'Payment method',
  'মাধ্যম পরিবর্তন': 'Change method',
  'আরও মাধ্যম': 'More methods',
  'জমার মাধ্যম': 'Deposit method',
  'নগদ জমা': 'Cash deposit',
  'নগদ প্রদান (ঐচ্ছিক)': 'Cash payment (optional)',
  'টাকার পরিমাণ': 'Amount',
  'টাকার পরিমাণ লিখুন': 'Enter amount',
  'জমা': 'Deposit',
  'জমা যোগ': 'Add deposit',
  'জমা পরিমাণ': 'Deposit amount',
  'জমা পরিমাণ লিখুন': 'Enter deposit amount',
  'জমা সম্পাদন': 'Edit deposit',
  'জমা ডিলিট?': 'Delete deposit?',
  'কোনো জমা নেই': 'No deposits',
  'এই জমা এন্ট্রি মুছে ফেলা হবে।': 'This deposit entry will be deleted.',
  'নতুন জমার পরিমাণ আপডেট করুন': 'Update the new deposit amount',
  'আজকের জমা': "Today's deposits",
  'মোট জমা': 'Total deposits',
  'জমা: ফেরত বাবদ': 'Deposit: for returns',
  'জমা: রিপ্লেস বাবদ': 'Deposit: for replaces',
  'এই টাকা কাস্টমারের জমা হিসাবে যোগ হবে':
      "This amount will be added to the customer's credit",

  // বাকি / দেনা
  'বাকি': 'Due',
  'বাকি আছে': 'Due',
  'বাকি জমা': 'Due collection',
  'বাকি জমা করুন': 'Collect due',
  'বাকি জমা হয়েছে': 'Due collected',
  'বাকি সম্পাদন': 'Edit due',
  'বাকি আপডেট ব্যর্থ': 'Due update failed',
  'বাকি তালিকা': 'Due list',
  'কোনো বাকি নেই': 'No dues',
  'মোট বাকি': 'Total due',
  'মোট দেনা': 'Total payable',
  'নতুন বাকি': 'New due',
  'পূর্বের বাকি': 'Previous due',
  'পূর্বের বাকি (ডেলিভারির সময়)': 'Previous due (at delivery)',
  'পূর্বের বাকি সম্পাদন': 'Edit previous due',
  'আজকের বাকি': "Today's due",
  'আজকের বাকি কালেকশন': "Today's due collection",
  'কাস্টমার বাকি': 'Customer due',
  'বাকির চেয়ে বেশি টাকা দেওয়া যাবে না': 'Cannot pay more than the due amount',
  'দিতে হবে': 'To pay',

  // ফেরত / ডিসকাউন্ট / রিপ্লেস (অর্ডার)
  'ফেরত প্রডাক্ট': 'Returned product',
  'ফেরত প্রডাক্ট যোগ': 'Add returned product',
  'ফেরত প্রডাক্ট স্টকে যোগ করা যায়নি':
      'Could not add returned product to stock',
  'ফেরত বাদ': 'Return deduction',
  'ফেরত বাদ যোগ': 'Add return deduction',
  'ফেরত বাদ সম্পাদন': 'Edit return deduction',
  'মোট ফেরত মূল্য': 'Total return value',
  'ডিসকাউন্ট': 'Discount',
  'ডিসকাউন্ট (বাদ)': 'Discount (deducted)',
  'ডিসকাউন্ট যোগ': 'Add discount',
  'ডিসকাউন্ট সম্পাদন': 'Edit discount',
  'যদি ডিসকাউন্ট দিতে চান': 'If you want to give a discount',
  'টাকা কাটা': 'Money deducted',
  'রিপ্লেস প্রডাক্ট': 'Replace product',
  'রিপ্লেস প্রডাক্ট যোগ': 'Add replace product',
  'রিপ্লেস প্রডাক্ট যোগ হয়েছে': 'Replace product added',
  'রিপ্লেস আইটেম সরানো হয়েছে': 'Replace item removed',
  'রিপ্লেস সরাবেন?': 'Remove this replace?',
  'রিপ্লেস দিতে হবে': 'Replace to be given',
  'রিপ্লেস দেওয়া হল': 'Replace given',
  'রিপ্লেস নেওয়া হল': 'Replace received',
  'রিপ্লেস বাবদ বাদ': 'Deducted for replace',
  'রিপ্লেস বাবদ যোগ': 'Add replace deduction',
  'রিপ্লেস বাবদ সম্পাদন': 'Edit replace deduction',
  'রিপ্লেস বাবদ': 'For replace',
  'রিপ্লেস স্ট্যাটাস': 'Replace status',
  'রিপ্লেস ডেলিভারি সম্পন্ন হয়নি': 'Replace delivery not completed',
  'রিপ্লেস প্রসেসিং সম্পন্ন হয়নি': 'Replace processing not completed',
  'হস্তান্তরযোগ্য রিপ্লেস': 'Transferable replace',

  // মেমো ও হিসাব
  'মেমো হিসাব': 'Memo summary',
  'লোকাল মেমো': 'Local memo',
  'লোকাল মেমো নাম্বার': 'Local memo number',
  'লোকাল মেমো যোগ': 'Add local memo',
  'লোকাল মেমো আপডেট': 'Update local memo',
  'যেমন: 233': 'e.g. 233',
  'টোটাল': 'Total',
  'মোট পরিমাণ': 'Total amount',
  'নেট বিক্রি': 'Net sales',
  'নিট লাভ': 'Net profit',
  'লাভের হার': 'Margin',
  'লাভের হিসাব': 'Profit breakdown',
  'পরিবর্তন সেভ করুন': 'Save changes',

  // ── প্রোডাক্ট / Product ──
  'পণ্যের তথ্য': 'Product info',
  'পণ্যের নাম *': 'Product name *',
  'পণ্যের নাম লিখুন...': 'Enter product name…',
  'পণ্য *': 'Product *',
  'প্রডাক্ট *': 'Product *',
  'পণ্য এডিট করুন': 'Edit product',
  'পণ্য আপডেট হয়েছে': 'Product updated',
  'পণ্য খুঁজুন...': 'Search product…',
  'পণ্য সিলেক্ট করুন': 'Select product',
  'প্রডাক্ট সিলেক্ট করুন': 'Select product',
  'প্রডাক্ট নির্বাচন করুন': 'Select a product',
  'একটি প্রডাক্ট বেছে নিন': 'Pick a product',
  'প্রডাক্ট বেছে নিন *': 'Pick a product *',
  'পণ্য ডিলেট করবেন?': 'Delete this product?',
  'পণ্য ডিলেট করুন': 'Delete product',
  'Product ডিলেট করবেন?': 'Delete this product?',
  'Product ডিলেট করুন': 'Delete product',
  'নতুন Product যোগ করুন': 'Add a new product',
  'নাম আবশ্যক': 'Name is required',
  'Name ও Category আবশ্যক': 'Name and category are required',
  'মৌলিক তথ্য': 'Basic info',
  'ক্যাটাগরি': 'Category',
  'ক্যাটাগরি ও স্টক': 'Category and stock',
  'ব্র্যান্ড': 'Brand',
  'প্রোডাক্ট কোড': 'Product code',
  'ইউনিট (pcs/box/set)': 'Unit (pcs/box/set)',
  'ক্রয়মূল্য': 'Cost price',
  'পাইকারি': 'Wholesale',
  'পাইকারি মূল্য': 'Wholesale price',
  'খুচরা': 'Retail',
  'খুচরা মূল্য': 'Retail price',
  'মূল্য আপডেট (ঐচ্ছিক)': 'Update price (optional)',
  'ছবি (Image URLs)': 'Images (image URLs)',
  'Image URL paste করুন...': 'Paste an image URL…',
  'Product Details / বৈশিষ্ট্য': 'Product details / features',
  'যেমন: Color: Black, Power: 20W...': 'e.g. Color: Black, Power: 20W…',
  'YouTube / অন্য video URL': 'YouTube or other video URL',
  'Available (বিক্রয়যোগ্য)': 'Available (sellable)',
  'স্টক ও বিবরণ': 'Stock and details',

  // স্টক ম্যানেজমেন্ট
  'স্টক': 'Stock',
  'স্টক ম্যানেজমেন্ট': 'Stock management',
  'স্টক যোগ করুন': 'Add stock',
  'স্টক কমান': 'Reduce stock',
  'স্টক কমান (বিক্রি/ব্যবহার)': 'Reduce stock (sold/used)',
  'স্টক বাড়ান (ক্রয়/যোগ)': 'Increase stock (purchase/add)',
  'স্টক লিস্ট কপি করুন': 'Copy stock list',
  'নতুন স্টক পরিমাণ': 'New stock quantity',
  'কত যোগ করবেন?': 'How much to add?',
  'কত বাদ দেবেন?': 'How much to deduct?',
  'কমান': 'Reduce',
  'কমানো হয়েছে': 'Reduced',
  'সেট করুন': 'Set',
  'সব স্টক শূন্য করুন': 'Zero out all stock',
  'সব স্টক শূন্য করবেন?': 'Zero out all stock?',
  'সব স্টক শূন্য করা হয়েছে': 'All stock zeroed out',
  'হ্যাঁ, শূন্য করুন': 'Yes, zero it out',
  'সব পণ্যের স্টক ০ হয়ে যাবে। এই কাজটি পূর্বাবস্থায় ফেরানো যাবে না।':
      'Stock for every product will become 0. This cannot be undone.',
  'সব ডকুমেন্ট ঠিক করুন': 'Fix all documents',
  'সব ডকুমেন্ট ইতিমধ্যে সম্পূর্ণ ছিল।': 'All documents were already complete.',

  // স্ন্যাপশট
  'নতুন স্ন্যাপশট': 'New snapshot',
  'স্ন্যাপশট সেভ করুন': 'Save snapshot',
  'স্ন্যাপশট ডিলেট করবেন?': 'Delete this snapshot?',
  'স্টক স্ন্যাপশট ইতিহাস': 'Stock snapshot history',
  'এই স্ন্যাপশটে ফিরবেন?': 'Restore this snapshot?',
  'এই স্ন্যাপশটে ফিরুন': 'Restore this snapshot',
  'রিস্টোর করুন': 'Restore',
  'রিস্টোর সম্পন্ন': 'Restore complete',
  'লেবেল': 'Label',
  'লেবেল / নাম': 'Label / name',
  'কোনো স্ন্যাপশট নেই\nনিচের বাটনে চেপে স্টক সেভ করুন':
      'No snapshots yet\nTap the button below to save the current stock',

  // ইন্টার্নাল পণ্য
  'ইন্টার্নাল পণ্য': 'Internal product',
  'নতুন ইন্টার্নাল পণ্য': 'New internal product',
  'ইন্টার্নাল পণ্য যোগ হয়েছে': 'Internal product added',
  'কোনো ইন্টার্নাল পণ্য নেই\n(+ বাটন দিয়ে যোগ করুন)':
      'No internal products yet\n(use the + button to add one)',
  '── ইন্টার্নাল পণ্য ──': '── Internal products ──',
  '── রিপ্লেস পণ্য ──': '── Replace products ──',
  '── সকল পণ্য ──': '── All products ──',

  // প্রোডাক্ট রিপ্লেস
  'নতুন Replace যোগ করুন': 'Add a new replace',
  'Replace যোগ করুন': 'Add replace',
  'Replace বাতিল করবেন?': 'Cancel this replace?',
  'Replace অনুরোধ বাতিল করা হয়েছে': 'Replace request cancelled',
  'কোনো replace product নেই': 'No replace products',
  'কোনো পেন্ডিং replace নেই': 'No pending replaces',
  'কাস্টমার / শপ *': 'Customer / shop *',
  'কাস্টমার/শপ সিলেক্ট করুন': 'Select a customer or shop',
  'শপের নাম লিখুন...': 'Enter shop name…',
  'শপ বা প্রডাক্ট নাম দিয়ে খুঁজুন...': 'Search by shop or product name…',
  'সমস্যার বিবরণ...': 'Describe the problem…',
  'ডেলিভারি দিয়েছি': 'Delivered',
  'দিয়েছি': 'Given',
  'ডেলিভারি নিশ্চিত করুন': 'Confirm delivery',
  'ডেলিভারি রেকর্ড মুছবেন?': 'Delete this delivery record?',
  'কোনো ডেলিভারি রেকর্ড নেই': 'No delivery records',
  'রেকর্ড মুছুন': 'Delete record',
  'বাতিল হয়েছে': 'Cancelled',

  // ── ক্রয় / Purchase ──
  'Purchase যোগ করুন': 'Add purchase',
  'Purchase entry মুছবেন?': 'Delete this purchase entry?',
  'এই মাসে কোনো purchase নেই': 'No purchases this month',
  'কমপক্ষে একটি প্রডাক্ট যোগ করুন': 'Add at least one product',
  'উপরে সার্চ করে প্রডাক্ট যোগ করুন': 'Search above to add products',
  'যোগ করা প্রডাক্টসমূহ': 'Added products',
  'প্রডাক্ট সার্চ করুন...': 'Search products…',
  'মাসের মোট কেনা': 'Total purchased this month',
  'মোট কেনা': 'Total purchased',
  '৳ মূল্য': '৳ price',
  '✓ কার্টে আছে': '✓ In cart',
  'কোনো approved অর্ডার নেই': 'No approved orders',
  'কোনো শর্ট প্রডাক্ট নেই': 'No short products',
  'শর্ট': 'Short',
  'সংগ্রহ করা লাগবে': 'Needs to be procured',
  'সংগ্রহ তালিকা': 'Procurement list',
  'সংগ্রহ তালিকা ক্লিপবোর্ডে কপি হয়েছে':
      'Procurement list copied to clipboard',
  'তালিকা কপি করুন': 'Copy list',
  'সংক্ষিপ্ত কপি': 'Copy short list',
  'সংক্ষিপ্ত তালিকা কপি হয়েছে': 'Short list copied',
  'সব প্রডাক্ট স্টকে আছে — শর্ট নেই!': 'All products in stock — nothing short!',
  'সাপ্লাইয়ার বেছে নিন': 'Pick a supplier',
  'সাপ্লাইয়ার বেছে নিন *': 'Pick a supplier *',
  'সাপ্লাইয়ার সার্চ করুন...': 'Search suppliers…',
  'লোড করতে সমস্যা হয়েছে': 'Failed to load',

  // ── রিপ্লেস ম্যানেজমেন্ট / Replace ──
  'At Shop যোগ করুন': 'Add to at-shop',
  'Supplier এ যোগ করুন': 'Add to supplier',
  'Customer বেছে নিন': 'Pick a customer',
  'Customer বেছে নিন *': 'Pick a customer *',
  'Customer বেছে নিন (ঐচ্ছিক)': 'Pick a customer (optional)',
  'কাস্টমার বেছে নিন (ঐচ্ছিক)': 'Pick a customer (optional)',
  'Defective product বেছে নিন': 'Pick the defective product',
  'Replace product বেছে নিন': 'Pick the replace product',
  'Replace entry সফলভাবে যোগ হয়েছে': 'Replace entry added successfully',
  'Deduction Amount (৳)': 'Deduction amount (৳)',
  'অজানা কাস্টমার': 'Unknown customer',
  'অপেক্ষমাণ': 'Pending',
  'কাস্টমার কি দিচ্ছে? (সমস্যার প্রডাক্ট)':
      'What is the customer returning? (faulty product)',
  'কাস্টমার কি পাবে? (ঐচ্ছিক)': 'What will the customer receive? (optional)',
  'কাস্টমার ডেলিভারি পেন্ডিং': 'Customer delivery pending',
  'কাস্টমার থেকে': 'From customer',
  'কাস্টমারকে ডেলিভারি দিন': 'Deliver to customer',
  'কাস্টমারকে দেওয়া হয়েছে': 'Given to customer',
  'সব কাস্টমারকে ডেলিভারি দেওয়া হয়েছে': 'Delivered to all customers',
  'কোথায় যাবে?': 'Where does it go?',
  'কোনো customer পাওয়া যায়নি': 'No customers found',
  'কোনো ইতিহাস নেই': 'No history',
  'কোনো কাস্টমার রিপ্লেস এন্ট্রি নেই': 'No customer replace entries',
  'কোনো পেন্ডিং রিপ্লেস ডেলিভারি নেই': 'No pending replace deliveries',
  'কোনো রিপ্লেস প্রডাক্ট নেই': 'No replace products',
  'ডেলিভারি দেওয়া হয়েছে': 'Delivered',
  'দিয়েছিল:': 'Gave:',
  'পাবে:': 'Will receive:',
  'দোকানে আছে': 'At shop',
  'দোকানে কোনো replace item নেই': 'No replace items at the shop',
  'দোকানে মেরামত': 'Repair at shop',
  'দোকানের নাম, ফোন বা ঠিকানা দিয়ে সার্চ করুন...':
      'Search by shop name, phone or address…',
  'নতুনের মতো — সাধারণ স্টকে রাখুন': 'Like new — put in regular stock',
  'মেরামত অযোগ্য — ফেলে দিন': 'Beyond repair — discard',
  'মেরামত/পরিবর্তিত — রিপ্লেস স্টক হিসেবে রাখুন':
      'Repaired/refurbished — keep as replace stock',
  'পরিমাণ পরিবর্তন (+/-):': 'Change quantity (+/-):',
  'যেমন: 5 (যোগ) বা -3 (বাদ)': 'e.g. 5 (add) or -3 (subtract)',
  'যোগ করতে +, বাদ দিতে - ব্যবহার করুন': 'Use + to add and - to subtract',
  'পরিস্থিতি নির্ধারণ': 'Set resolution',
  'রেজোলিউশন পেন্ডিং': 'Resolution pending',
  'পাঠানো হয়েছে': 'Sent',
  'পাঠিয়ে দিন': 'Send',
  'প্রোডাক্ট সেট': 'Product set',
  'ফেরত দিয়েছে': 'Returned',
  'ফেরত পেলাম': 'Received back',
  'বাতিল করা হয়েছে': 'Cancelled',
  'রিপ্লেস প্রোডাক্ট নির্ধারিত নয়': 'Replace product not set',
  'রিপ্লেস স্টক ক্লিয়ার করবেন?': 'Clear replace stock?',
  'রিপ্লেস স্টক ০ করা হয়েছে': 'Replace stock set to 0',
  'রিপ্লেস স্টকে যোগ করুন': 'Add to replace stock',
  'রিপ্লেস স্টকে যোগ হয়েছে': 'Added to replace stock',
  'রেগুলার স্টকে যোগ করুন': 'Add to regular stock',
  'রেগুলার স্টকে যোগ হয়েছে': 'Added to regular stock',
  'সাপ্লাইয়ার ফেরত': 'Supplier return',
  'সাপ্লাইয়ারে আছে': 'At supplier',
  'সাপ্লাইয়ারে কোনো আইটেম নেই': 'No items at the supplier',
  'সাপ্লাইয়ারে পাঠান': 'Send to supplier',
  'সাপ্লাইয়ারে পাঠানো': 'Sent to supplier',
  'সাপ্লাইয়ারে সরাসরি এন্ট্রি যোগ হয়েছে': 'Direct supplier entry added',

  // ── বিক্রয় / Sales ──
  'Gross বিক্রি': 'Gross sales',
  'SR কাছে বাকি:': 'Held by SR:',
  'SR পাওনা:': 'SR receivable:',
  'SR জমা': 'SR deposit',
  'SR জমা যোগ': 'Add SR deposit',
  'SR ব্যালেন্স': 'SR balance',
  'SR হাতে টাকা': 'Cash in SR hand',
  'জমা: SR হাতে': 'Deposit: with SR',
  'অ্যাডজাস্টমেন্ট': 'Adjustment',
  'এই সময়ের মধ্যে কোনো ডাটা নেই': 'No data in this period',
  'কোনো পেমেন্ট নেই': 'No payments',
  'দিনওয়ারি বিবরণ': 'Day-wise breakdown',
  'দৈনিক বিবরণ': 'Daily breakdown',
  'পেমেন্ট মাধ্যম ভিত্তিক জমা': 'Deposits by payment method',
  'বিকাশ/অন্যান্য': 'bKash / other',

  // ── বিক্রয় পরিকল্পনা / Sales plan ──
  'Actual রিফ্রেশ করুন': 'Refresh actuals',
  'অন্তত একটি প্রডাক্ট যোগ করুন': 'Add at least one product',
  'অর্জন': 'Achieved',
  'অর্জন %': 'Achieved %',
  'কাস্টমার বিক্রয় পরিকল্পনা': 'Customer sales plan',
  'কাস্টমার বাদ দেবেন?': 'Remove this customer?',
  'কাস্টমার যোগ করুন': 'Add customer',
  'কাস্টমার যোগ করতে নিচের + বোতাম চাপুন':
      'Tap the + button below to add a customer',
  'কাস্টমার সিলেক্ট করুন': 'Select a customer',
  'কোনো প্রডাক্ট যোগ করা হয়নি': 'No products added',
  'দায়িত্বপ্রাপ্ত SR': 'Assigned SR',
  'নতুন পরিকল্পনা': 'New plan',
  'ডেটা লোড হয়নি। পুনরায় চেষ্টা করুন।':
      'Data failed to load. Please try again.',
  'পরিকল্পনা ডিলেট করবেন?': 'Delete this plan?',
  'পরিকল্পনা ডিলেট করুন': 'Delete plan',
  'পরিকল্পনার বাইরে বিক্রীত': 'Sold outside the plan',
  'পরিকল্পনার শিরোনাম': 'Plan title',
  'পরিমাণ ০-এর বেশি হতে হবে': 'Quantity must be greater than 0',
  'প্রডাক্ট ও লক্ষ্যমাত্রা': 'Products and targets',
  'প্রডাক্ট যোগ করুন': 'Add product',
  'প্রডাক্টওয়ারি অর্জন': 'Achievement by product',
  'প্রথমে একটি প্রডাক্ট সিলেক্ট করুন': 'Select a product first',
  'মোট লক্ষ্য': 'Total target',
  'যেমন: মে মাসের লক্ষ্যমাত্রা': 'e.g. target for May',
  'লক্ষ্যমাত্রা (টাকা)': 'Target (৳)',
  'লক্ষ্যমাত্রা (টাকা) *': 'Target (৳) *',
  'লক্ষ্যমাত্রা (টি)': 'Target (qty)',
  'লক্ষ্যমাত্রা পরিবর্তন': 'Change target',
  'লক্ষ্যমাত্রা ০-এর বেশি হতে হবে': 'Target must be greater than 0',
  'সকল SR': 'All SRs',
  'সকল SR (সামগ্রিক)': 'All SRs (overall)',
  'সামগ্রিক অগ্রগতি': 'Overall progress',
  'সামগ্রিক অর্জন': 'Overall achievement',
  '✓ পূরণ': '✓ Met',
  '✓ লক্ষ্য পূরণ': '✓ Target met',

  // মাসের নাম
  'জানুয়ারি': 'January',
  'ফেব্রুয়ারি': 'February',
  'মার্চ': 'March',
  'এপ্রিল': 'April',
  'মে': 'May',
  'জুন': 'June',
  'জুলাই': 'July',
  'আগস্ট': 'August',
  'সেপ্টেম্বর': 'September',
  'অক্টোবর': 'October',
  'নভেম্বর': 'November',
  'ডিসেম্বর': 'December',
  'জানু': 'Jan',
  'ফেব্রু': 'Feb',
  'সেপ্ট': 'Sep',
  'অক্টো': 'Oct',
  'নভে': 'Nov',
  'ডিসে': 'Dec',

  // ── SR ব্যবস্থাপনা / SR management ──
  'SR ব্যবস্থাপনা': 'SR management',
  'SR সম্পাদনা': 'Edit SR',
  'SR মুছবেন?': 'Delete this SR?',
  'নতুন SR যোগ করুন': 'Add a new SR',
  'কোনো SR পাওয়া যায়নি': 'No SRs found',
  'SR এর ইমেইল আবশ্যক': "The SR's email is required",
  'SR এর ইমেইল নেই': 'This SR has no email',
  'SR এর অ্যাকাউন্ট এখনো তৈরি হয়নি':
      "The SR's account has not been created yet",
  'এই SR এর Firebase অ্যাকাউন্ট এখনো তৈরি হয়নি।':
      "This SR's Firebase account has not been created yet.",
  'নাম *': 'Name *',
  'নাম লিখুন': 'Enter name',
  'ইমেইল': 'Email',
  'ইমেইল আবশ্যক': 'Email is required',
  'ইমেইল (লগইনের জন্য) *': 'Email (for login) *',
  'সঠিক ইমেইল দিন': 'Enter a valid email',
  'এই ইমেইল ইতিমধ্যে ব্যবহৃত হচ্ছে': 'This email is already in use',
  'ফোন নং *': 'Phone number *',
  'ফোন নং লিখুন': 'Enter phone number',
  'ফোন নম্বর': 'Phone number',
  'পাসওয়ার্ড': 'Password',
  'পাসওয়ার্ড *': 'Password *',
  'পাসওয়ার্ড দিন': 'Enter a password',
  'পাসওয়ার্ড নিশ্চিত করুন *': 'Confirm password *',
  'পাসওয়ার্ড মিলছে না': 'Passwords do not match',
  'পাসওয়ার্ড রিসেট লিংক পাঠানো হয়েছে': 'Password reset link sent',
  'লগইন পাসওয়ার্ড': 'Login password',
  'লগইন আছে': 'Has login',
  'লগইন নেই': 'No login',
  'লিংক পাঠান': 'Send link',
  'কমপক্ষে ৬ অক্ষর': 'At least 6 characters',
  'কমিশন % *': 'Commission % *',
  'কমিশন % লিখুন': 'Enter commission %',
  'মাসিক বেতন (৳) *': 'Monthly salary (৳) *',
  'বেতন লিখুন': 'Enter salary',
  'বাকি লিমিট': 'Due limit',
  'বাকি লিমিট (৳) *': 'Due limit (৳) *',
  'বাকি লিমিট লিখুন': 'Enter due limit',
  'সক্রিয়': 'Active',
  'নিষ্ক্রিয়': 'Inactive',
  'অনুমোদিত': 'Approved',
  'পারফরম্যান্স': 'Performance',
  'বিক্রয়': 'Sales',
  'অতিরিক্ত (ফ্রিজড)': 'Excess (frozen)',
  'অতিরিক্ত বাকি আদায় করলে ফ্রিজ মুক্ত হবে।':
      'Collecting the excess due will unfreeze it.',
  'ফ্রিজড': 'Frozen',
  'গ্রাহক বাকি ট্র্যাকার': 'Customer due tracker',
  'মোট গ্রাহক বাকি': 'Total customer due',
  'মোট প্রাপ্য': 'Total receivable',
  'নেট প্রদেয়': 'Net payable',
  'পরিশোধিত': 'Paid',
  'সম্পূর্ণ পরিশোধিত': 'Fully paid',
  'পেমেন্ট ইতিহাস': 'Payment history',
  'পেমেন্ট রেকর্ড': 'Payment record',
  'পেমেন্ট রেকর্ড করুন': 'Record a payment',
  'পেমেন্ট মুছবেন?': 'Delete this payment?',
  'এই মাসের সারসংক্ষেপ': "This month's summary",
  'এই মাসের হিসাব': "This month's accounts",
  'অ্যাসাইন': 'Assign',
  'অ্যাসাইন সরান': 'Unassign',
  'দোকান নির্ধারণ': 'Assign shops',
  'দোকান যোগ করুন': 'Add shop',
  'নির্ধারিত দোকান': 'Assigned shops',
  'অন্যান্য দোকান': 'Other shops',
  'কোনো দোকান নির্ধারিত নেই': 'No shops assigned',
  'দোকান বন্ধ': 'Shop closed',
  'ডেলিভারি অ্যাসাইন': 'Assign delivery',
  'ডেলিভারি তালিকা': 'Delivery list',
  'ডেলিভারি দিন নির্ধারণ করুন': 'Set delivery day',
  'ডেলিভারি দিন সরান': 'Clear delivery day',
  'ভিজিট তালিকা': 'Visit list',
  'ভিজিট তালিকায় দোকানের ডেলিভারি দিন নির্ধারণ করুন':
      'Set delivery days for the shops on the visit list',
  'ভিজিট সম্পন্ন': 'Visit done',
  'ভিজিট স্ট্যাটাস': 'Visit status',
  'ভিজিট স্ট্যাটাস দিন': 'Set visit status',
  'আজকের ভিজিট': "Today's visits",
  'কল তালিকা': 'Call list',
  'কল তালিকায় যোগ': 'Add to call list',
  'কল তালিকায় যোগ করুন': 'Add to the call list',
  'কোনো কল তালিকা নেই': 'Call list is empty',
  'কল পরিচিতি': 'Call contacts',
  'অপেক্ষারত': 'Waiting',
  'অর্ডার দিবেনা': 'Will not order',
  'অর্ডার পরে দিবে': 'Will order later',
  'অর্ডার সম্পন্ন': 'Order placed',
  '— স্ট্যাটাস স্থির করুন —': '— Set a status —',

  // ── SR প্যানেল / SR panel ──
  'SR প্যানেল': 'SR panel',
  'ড্যাশবোর্ড': 'Dashboard',
  'আমার': 'Mine',
  'আমার অর্ডার': 'My orders',
  'আমার দোকান': 'My shops',
  'আমার কাটা': 'My deductions',
  'ইউজার': 'User',
  'ইউজার তালিকা': 'User list',
  'সকল ইউজার': 'All users',
  'কোনো ইউজার পাওয়া যায়নি': 'No users found',
  'কোনো ফলাফল পাওয়া যায়নি': 'No results found',
  'গ্রাহক সংখ্যা': 'Customer count',
  'তালিকা থেকে বাদ দিন': 'Remove from list',
  'তালিকা থেকে বাদ দিবেন?': 'Remove from the list?',
  'এই SR-এর কোনো নির্ধারিত দোকান নেই। Admin থেকে দোকান নির্ধারিত করলে এখানে আলাদা সেকশনে দেখাবে।':
      'This SR has no assigned shops. Once an admin assigns shops, they will appear here in a separate section.',

  // ── স্টক ইন / Stock in ──
  'স্টক ইন যোগ': 'Add stock in',
  'নতুন স্টক ইন': 'New stock in',
  'স্টক ইন ইতিহাস': 'Stock-in history',
  'কোনো স্টক ইন এন্ট্রি নেই': 'No stock-in entries',
  'কোনো এন্ট্রি পাওয়া যায়নি': 'No entries found',
  'স্টক এডজাস্ট হয়েছে': 'Stock adjusted',
  'তারিখ আপডেট হয়েছে': 'Date updated',
  'পরিমাণ ১+ হতে হবে': 'Quantity must be at least 1',
  'দাম:': 'Price:',
  'প্রডাক্টসমূহ': 'Products',
  'সোর্স (কোথা থেকে)': 'Source (from where)',
  'যেমন: ঢাকা, চট্টগ্রাম': 'e.g. Dhaka, Chattogram',
  'কোনো নোট থাকলে লিখুন': 'Add a note if you have one',
  'প্রডাক্ট নাম, সোর্স বা নোট দিয়ে খুঁজুন…':
      'Search by product name, source or note…',

  // ── সাপ্লাইয়ার / Supplier ──
  'নতুন সাপ্লাইয়ার': 'New supplier',
  'সাপ্লাইয়ার যোগ করুন': 'Add supplier',
  'সাপ্লাইয়ার সম্পাদনা': 'Edit supplier',
  'সাপ্লাইয়ার মুছবেন?': 'Delete this supplier?',
  'কোনো সাপ্লাইয়ার নেই': 'No suppliers',
  'কোনো সাপ্লাইয়ার নেই। আগে সাপ্লাইয়ার যোগ করুন।':
      'No suppliers yet. Add a supplier first.',
  'নিচের + বোতাম চাপুন সাপ্লাইয়ার যোগ করতে':
      'Tap the + button below to add a supplier',
  'দোকানের নাম *': 'Shop name *',
  'দোকানের নাম আবশ্যিক': 'Shop name is required',
  'মালিকের নাম': "Owner's name",
  'ঠিকানা': 'Address',
  'ক্রয় ইতিহাস': 'Purchase history',
  'মোট ক্রয়': 'Total purchases',
  'এই সাপ্লাইয়ারের কোনো ক্রয় নেই': 'No purchases from this supplier',
  'সংরক্ষণ করতে সমস্যা হয়েছে': 'Could not save',

  // ── ইউজার / User ──
  'Replace মুছবেন?': 'Delete this replace?',
  'কোনো order নেই': 'No orders',
  'কোনো replace নেই': 'No replaces',
  'কোনো user পাওয়া যায়নি': 'No users found',
  'নিচের + বাটনে ক্লিক করে যোগ করুন': 'Tap the + button below to add one',
  'বাকি পাওনা সম্পাদনা': 'Edit outstanding due',
  'মোট বাকি পাওনা': 'Total outstanding due',

  // ── interpolated স্ট্রিংয়ের ভেতরের স্থির অংশ ──
  // যেমন 'স্টক: ${p.stock}' → '${'স্টক'.tr}: ${p.stock}'
  'পণ্য': 'products',
  'রেগুলার': 'Regular',
  'রিপ্লেস স্টক': 'Replace stock',
  'বর্তমান রিপ্লেস স্টক': 'Current replace stock',
  'বর্তমান স্টক': 'Current stock',
  'এন্ট্রি': 'entries',
  'টি এন্ট্রি': ' entries',
  'টি প্রডাক্ট': ' products',
  'টি পণ্য': ' products',
  'টি অর্ডার': ' orders',
  'টি ডেলিভারি': ' deliveries',
  'টি পেন্ডিং': ' pending',
  'টি সম্পন্ন': ' done',
  'টি রিজলভড': ' resolved',
  'টি সিলেক্ট': ' selected',
  'টি বেছেছেন': ' selected',
  'টি হস্তান্তর': ' transferred',
  'টি দোকান নির্বাচিত': ' shops selected',
  'টি কাস্টমার রিপ্লেস': ' customer replaces',
  'টি পেন্ডিং ডেলিভারি': ' pending deliveries',
  'টি আইটেম সাপ্লাইয়ারে': ' items at supplier',
  'জন কাস্টমার ডেলিভারি পেন্ডিং': ' customers with delivery pending',
  'টি রিপ্লেস ডেলিভারি': ' replace deliveries',
  'টি ফেরত রিপ্লেস': ' returned replaces',
  'টি বিক্রি হয়েছে': ' sold',
  'টি ডকুমেন্ট আপডেট হয়েছে': ' documents updated',
  'টি পণ্য কপি হয়েছে': ' products copied',
  'জন': ' people',
  'শপ': 'Shop',
  'মালিক': 'Owner',
  'ফোন': 'Phone',
  'অর্ডারে': 'in order',
  'পরবর্তী': 'Next',
  'বকেয়া': 'Outstanding',
  'বর্তমান বাকি': 'Current due',
  'রিজলভড': 'Resolved',
  'পাঠানো': 'Sent',
  'দিয়েছে': 'Gave',
  'মিস': 'Missed',
  'কন্টাক্ট': 'Contact',
  'দোকান': 'Shop',
  'ডেলিভারি দিন': 'Delivery day',
  'ডেলিভারি দিন নির্বাচন': 'Select delivery day',
  'কোনো ডেলিভারি নেই': 'No deliveries',
  'সকল': 'All',
  'ডিসপ্যাচ': 'Dispatch',
  'ম্যানুয়াল স্টক আউট': 'Manual stock out',
  'স্ন্যাপশট সংরক্ষিত': 'Snapshot saved',
  'রিপ্লেস পণ্য': 'Replace products',
  'পাসওয়ার্ড রিসেট': 'Password reset',
  'বেতন ফ্রিজ': 'Salary frozen',
  'বাকি লিমিট ছাড়িয়ে গেছে': 'Due limit exceeded',
  'অতিরিক্ত পরিশোধিত': 'Overpaid',
  'অ্যাকাউন্ট তৈরি ব্যর্থ': 'Account creation failed',
  'সফলভাবে আপডেট হয়েছে': 'updated successfully',
  'সফলভাবে আপডেট করা হয়েছে': 'updated successfully',
  'সফলভাবে যোগ করা হয়েছে': 'added successfully',
  'সরিয়ে দেওয়া হয়েছে': 'removed',
  'সাপ্লাইয়ারে পাঠানো হয়েছে': 'sent to supplier',
  'স্থায়ীভাবে মুছে যাবে': 'will be permanently deleted',
  'স্থায়ীভাবে মুছে ফেলা হবে': 'will be permanently deleted',
  'পাওয়া যায়নি': 'not found',
  'দেওয়া হয়েছে': 'given',
  'পরিবর্তন হয়েছে': 'changed',
  'আপডেট হবে': 'will be updated',
  'স্টক কমে যাবে': 'stock will be reduced',
  'স্টক ইন হয়েছে': 'stocked in',
  'স্টক ইন করুন': 'Stock in',
  'স্টক আউট সম্পন্ন হয়েছে': 'stock out completed',
  'স্টক অপরিবর্তিত থাকবে': 'stock will stay unchanged',
  'স্টক থেকে মাইনাস হয়েছে': 'deducted from stock',
  'সাবমিট করতে ব্যর্থ': 'failed to submit',
  'অর্ডার সাবমিট করতে ব্যর্থ': 'failed to submit the order',
  'অর্ডার করতে ব্যর্থ': 'failed to place the order',
  'সরানো যায়নি': 'could not be removed',
  'যোগ হয়নি': 'was not added',
  'ডেলিভারি সম্পন্ন হয়নি': 'delivery not completed',
  'রিপ্লেস আইটেম সরিয়ে দিতে চান': 'remove this replace item',
  'এই অর্ডার থেকে রিমুভ করতে চান': 'remove from this order',
  'ভিজিট তালিকা থেকে বাদ দিতে চান': 'remove from the visit list',
  'ডিলিট করবেন': 'Delete',
  'করতে চান': 'do you want to',
  'হ্যালো': 'Hello',
  'লোকাল': 'Local',
  'পরিকল্পনা সেভ হয়েছে': 'plan saved',
  'পরিকল্পনায় যোগ হয়েছে': 'added to the plan',
  'এই মাসের পরিকল্পনা থেকে বাদ যাবে': 'will be removed from this month\'s plan',
  'লক্ষ্য ছাড়িয়ে অতিরিক্ত': 'above target by',
  'শর্ট প্রডাক্ট': 'short products',
  'তথ্য নেই': 'No data',
  'করলে স্টক কেটে যাবে': 'will deduct stock',
  'এন্ট্রিটি মুছে যাবে': 'entry will be deleted',
  'টি রিপ্লেস স্টক ০ করা হবে': ' replace stocks will be set to 0',
  'টি রিপ্লেস পণ্যের বর্তমান স্টক সেভ হবে':
      ' replace products\' current stock will be saved',
  'ইন্টার্নাল পণ্য এবং দোকানের রিপ্লেস স্টক রিস্টোর হবে':
      'internal products and at-shop replace stock will be restored',
  'বর্তমান স্টক অবস্থা ওভাররাইট হবে':
      'the current stock state will be overwritten',
  'স্ন্যাপশটের পরবর্তী সকল ম্যানুয়াল স্টক আউট ও ডিসপ্যাচ রিভার্ট হবে':
      'every manual stock out and dispatch after the snapshot will be reverted',
  'ঠিকানায় একটি পাসওয়ার্ড রিসেট লিংক পাঠানো হবে':
      'a password reset link will be sent to this address',
  'সেই লিংক ব্যবহার করে নতুন পাসওয়ার্ড সেট করতে পারবে':
      'they can set a new password using that link',
  'এ একটি রিসেট লিংক পাঠানো হয়েছে': 'a reset link has been sent to',
  'এর সমস্ত তথ্য মুছে যাবে': "all of this record's data will be deleted",
  'এর অর্ডার': "'s orders",
  'অনুযায়ী সকল পণ্য': 'all products by',
  'কমিশন': 'Commission',
  'স্ন্যাপশট কপি হয়েছে': 'snapshot copied',
  'ডিফল্ট ক্রয়মূল্য': 'Default cost price',
  'Approved অর্ডার': 'Approved orders',
};
